@startuml 

hide empty members

class Saal {
    * id : int
    name : string

}

class Sitzplatz{
    * id : int 
    saalId : int
    reihe : int 
    sitz : int
    preis : double
}

class Sitzplatzangebot{
    * id : int 
    sitzplatzId : int 
    vorstellungsId : int 
    reservationsId : int 
}
class Zeitfenster {
    * id : int 
    startzeit : DateTime 
    endzeit : DateTime
}

class Film {
    * id : int 
    name : string 
    regisseur : string 
}

class Vorstellung{
    * id : int 
    zeitfensterId : int 
    saalId : int 
    filmId : int 
}

class Reservation{
    * id : int 
    name : string 
    email : string 
}


Film ||---|{ Vorstellung
Saal ||---|{ Vorstellung
Zeitfenster ||---|{ Vorstellung
Saal ||---|{ Sitzplatz 


Reservation |o---|{ Sitzplatzangebot
Sitzplatz ||---|| Sitzplatzangebot
Vorstellung ||---|{ Sitzplatzangebot
@enduml